version: "3.9"

services:
  myapp:
    build: .
    container_name: ecommerce-myapp
    ports:
      - "80:80"
    volumes:
      - myapp_data:/usr/share/nginx/html   # ðŸ‘ˆ DATA SAFE
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-krushna
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS: "false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-krushna
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-krush-jagdale
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  myapp_data:          # ðŸ‘ˆ NEW
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  prometheus_data:
  grafana_data:
