version: "3.9"

services:
  myapp:
    build: .
    container_name: ecommerce-myapp
    ports:
      - "80:80"
    volumes:
      - myapp_data:/usr/share/nginx/html
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-krushna
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS: "false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: always

volumes:
  myapp_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
